### ISSUE TITLE
New release for compatibility with new JuliaInterpreter v0.5

### ISSUE THREAD

**Issue by fredrikekre** [timholy/Revise.jl#284] opened 2019-04-10 11:25 UTC
Currently you have to choose between latest JuliaInterpreter/Debugger and Revise 1.1, or old versions of JuliaInterpreter/Debugger and new Revise, e.g
```
(v1) pkg> add Debugger JuliaInterpreter Revise
 Resolving package versions...
  Updating `~/.julia/environments/v1/Project.toml`
  [31a5f54b] + Debugger v0.3.0
  [aa1ae85d] + JuliaInterpreter v0.4.1
  [295af30f] + Revise v2.1.1
```
or
```
(v1) pkg> add Debugger@0.4 JuliaInterpreter@0.5 Revise
 Resolving package versions...
  Updating `~/.julia/environments/v1/Project.toml`
  [31a5f54b] + Debugger v0.4.0
  [aa1ae85d] + JuliaInterpreter v0.5.0
  [295af30f] + Revise v1.1.0

```

**Comment by timholy** [comment] 2019-04-10 13:14
So, I've been using this to experiment with the best way to handle bounds:
- If one only declares lower bounds, things automatically work when a new version is released. OTOH, B depends on A, a new version of A breaks B, and B fixes it by releasing a new forward-compatible release, then the problem is that all older version of B are essentially broken by the fact that they didn't declare an upper bound on A.
- if one declares strict bounds, then someone has to manually certify each release. If the B's maintainer doesn't notice the situation quickly, then one gets issues like these.

My conclusion is that both strategies have their pain points. I'm not sure which is best. Thoughts?

**Comment by KristofferC** [comment] 2019-04-10 13:35
I don't see any good way of doing things except the way things are done now (declaring proper upper bounds). Blindly trusting that a new release (that has intentionally been marked as breaking by bumping a semver breaking version) is not breaking for a dependency (because of sheer luck) seems . Getting this wrong will mean that the resolver is quiet users getting potentially silent erroneous results, or, more likely, weird errors.

The only way to know if a dependency still works when that dependency has had a breaking is to test that dependency, verify it still works, and include that breaking release in `compat`. Yes, if a dependency often does multiple breaking releases then you need to release often as well, but there isn't really any alternative.

Right now, people are using Revise, it still works, but perhaps not everyone can use the latest version of all other packages. Instead of Revise perhaps being broken for everyone because of a breaking release of a dependency that wasn't upper bounded.

**Comment by fredrikekre** [comment] 2019-04-10 13:38
Right, so in the example here Revise is known to work with JuliaInterpreter 0.4 so here we should have
```
[compat]
JuliaInterpreter = "0.4"
```
Now that there is breaking JuliaInterpreter release we should verify that Revise work with it and then make a new release. It is a bit weird pre-1.0 since minor point releases are not always breaking in practice.

**Comment by timholy** [comment] 2019-04-10 16:13
Semver can't really handle it properly. `A` may have a release that's breaking for `B` but not `C`.

I *think* the best plan is to go with the one I'm trying, and manually certify releases. As it becomes more common to upper-bound packages, I think there will many instances where we want to bump constraints. I think I'll handle that by giving a wider number of trusted Julia developers the rights to certify new versions and tag new releases.

**Comment by timholy** [comment] 2019-04-10 16:13
Oh, and I'll test and then tag a new release.

**Comment by timholy** [comment] 2019-04-10 16:19
Closed by 09e26525bc0d4b2c8e78bf703d7def07041b8aca and https://github.com/JuliaLang/METADATA.jl/pull/22782

**Closed by timholy** 2019-04-10 16:19 UTC

**Comment by fredrikekre** [comment] 2019-04-10 16:22
Thanks!

**Comment by fredrikekre** [comment] 2019-04-10 16:23
See https://github.com/JuliaLang/METADATA.jl/pull/22782#issuecomment-481761496

**Comment by timholy** [comment] 2019-04-10 17:07
I retagged but nothing showed up over at METADATA. :man_shrugging:

**Comment by fredrikekre** [comment] 2019-04-10 20:38
> I retagged but nothing showed up over at METADATA. man_shrugging

Maybe you forgot to also delete the tag? I took the liberty to retry and seems to have worked now: https://github.com/JuliaLang/METADATA.jl/pull/22782#issuecomment-481852512

**Comment by timholy** [comment] 2019-04-10 22:36
I don't think I forgot, but maybe there was a stray or failed button click or something.
