### ISSUE TITLE
entr on directories calls function multiple times after a single save

### ISSUE THREAD

**Issue by bogiebro** [timholy/Revise.jl#476] opened 2020-05-06 21:58 UTC
Try watching a directory with the `entr` function. Save a file in the directory. You'll see that the function passed to `entr` is sometimes called multiple times. The exact number of times it's called seems pretty nondeterministic.

**Comment by bogiebro** [comment] 2020-05-06 22:17
This seems like a bug in `FileWatching.jl`

**Comment by timholy** [comment] 2020-05-07 13:10
"Bounces" in watching are common and depend on editor patterns and scheduling. For example, if you're editing `file.jl`, some editors will (1) save it as `file.jl~` and then if successful (2) `mv file.jl~ file.jl`. That prevents corruption if the save fails for some reason.

Revise's "core" (i.e., everything except `entr`) circumvents this by queuing unique actions and then running them the next time the user runs this at the REPL. You could mimic this in `entr` by having some latency before taking any action.

I'm marking this as "help wanted" because `entr` is community-supported.

**Comment by bogiebro** [comment] 2020-05-11 23:03
This only happens for me when watching directories. Watching individual files only triggers the function once using a delay of 0.1 seconds. Even when I set the delay as long as 2 seconds for directory watching, I get repeated function calls. This is easy to hack around by just listing directory contents and tracking the individual files instead, but it's a little confusing. This is for Arch Linux, Julia 1.4.1.

**Comment by ffevotte** [comment] 2020-06-07 12:16
I *think* this *might have been* fixed by #500... In any case, I can't manage to reproduce this on my system any more.

But better be sure: could you please test again with v2.7.2 and report whether this still happens?

**Comment by bogiebro** [comment] 2020-06-08 14:42
Yep, this seems to be fixed.

**Comment by ffevotte** [comment] 2020-06-08 16:08
Awesome! Thanks for the feedback!

**Closed by ffevotte** 2020-06-08 16:08 UTC
Labels: help wanted
