### ISSUE TITLE
Handle redefinition better

### ISSUE THREAD

**Issue by mfiano** [timholy/Revise.jl#328] opened 2019-08-13 05:47 UTC
Forgive me if this has been brought up before, but I just spent most of the day trying to solve a problem I had as a complete newcomer to Julia and Revise.jl:

During the initial stages of project development, I intend to create a module containing structs, and evolve them until their fields/types are finalized. As I read the other day, you can't really redefine types like this, so I thought Revise had some magic to reload the module or something. After trying various things unsuccessfully, I had a long thread on Slack where other users tried to help me with various solutions, also unsuccessfully, until it was suggested to try `include`ing the file to redefine the module.

This worked. I imagine this wouldn't be used very often, just as a project's types are still being sketched out, but it worked nonetheless. I was spending way too much time restarting Julia and reloading my code inbetween small edits. This is why I was looking for a solution.

This begs the question though: I think it would go a *long* way towards helping other newcomers if Revise.jl could handle the exception on `revise()` when a type has changed, and automatically issue an `include` call, perhaps even behind a user option if this is not desired by others. I'm too new to Julia to realize any problems this approach might have, but I'm just speaking as a newcomer trying to have an interactive coding environment that doesn't get in the way when fleshing out a new project. I hope this may spark some discussion on the matter anyway. Improving the live-coding capabilities of Julia would always be welcome in my opinion, coming from Common Lisp which is as interactive as can be.

That said, Revise is absolutely wonderful. Thanks for this!

**Comment by timholy** [comment] 2019-08-17 14:16
The problem with just redefining the module is that it only works if every time you want a `MyModule.MyType(5)` you scope it with the module name. If you've said `using MyModule` in Main, then `MyType(5)` will mean the old `MyType`, not the new one. A similar problem arises if package B relies on package A via a `using` statement. Consequently this strategy is really best for people who are handling everything manually, not something that a "use and forget" tool should implement.

IMO, the best strategy is to just fix the underlying problem. It's a lot of work though.

**Comment by timholy** [comment] 2019-08-17 14:17
This is a duplicate of many issues (e.g., #18) so I will close.

**Closed by timholy** 2019-08-17 14:17 UTC
