### ISSUE TITLE
"Multiple paths detected" error on JuliaBox

### ISSUE THREAD

**Issue by laser101** [timholy/Revise.jl#71] opened 2018-01-03 14:30 UTC
Attempts to use Revise.jl on JuliaBox result in the "Multiple paths detected" error when a package appears in both the preinstalled packages directory and the custom packages directory.

The error can be reproduced in the old or new JuliaBox implementation, and occurs both inside notebooks and when running Julia in the terminal.

The problem appears to be due to the fact that a package exists in both the directory containing the preinstalled packages and the user installed packages.

The following example illustrates the multiple paths issue.

```
julia> using Revise

julia> using StaticArrays

ERROR (unhandled task failure): Multiple paths detected: String["/mnt/juliabox/.julia/lib/v0.6/StaticArrays.ji", "/home/jrun/.julia/lib/v0.6/StaticArrays.ji"]
Stacktrace:
 [1] parse_pkg_files(::Symbol) at /////////mnt/juliabox/.julia/v0.6/Revise/src/Revise.jl:299
 [2] watch_package_impl at /////////mnt/juliabox/.julia/v0.6/Revise/src/Revise.jl:573 [inlined]
 [3] (::Revise.##9#10{Symbol})() at ./event.jl:73
julia>
```

In my case, the StaticArrays package was installed as a dependency when I installed the AstroLib package. It was installed to the following directory...

/mnt/juliabox/.julia/v0.6

However, the same package is also present as a JuliaBox preinstalled package in the following directory...

/home/jrun/.julia/v0.6

It would be nice if Revise could be used within the JuliaBox environment.

Russ

**Comment by timholy** [comment] 2018-02-06 11:34
Duplicate of #68

**Closed by timholy** 2018-02-06 11:34 UTC
