### ISSUE TITLE
Not sure it's working...

### ISSUE THREAD

**Issue by sbromberger** [timholy/Revise.jl#30] opened 2017-07-25 20:31 UTC
I'm making some changes to a function within VS Code and saving. The first couple of times, Revise appears to catch the change. If I revert the change (either using ^Z or manually changing things back, like deleting a line) and save the file, Revise sometimes fails to catch the change, even after a manual `revise()`.

**Comment by timholy** [comment] 2017-07-25 20:51
Ooof, not good. But I'm going to need more information to reproduce. Perhaps can you add a `@show wf` before [this line](https://github.com/timholy/Revise.jl/blob/0ab150ed5320b01851b3962e4f4c3a61b2e0b233/src/Revise.jl#L435) and replicate? Also `versioninfo` details would be helpful.

**Comment by timholy** [comment] 2017-07-25 20:54
Oh, I should add that Revise doesn't currently support *automatic* updates with Juno (see https://github.com/JunoLab/Atom.jl/issues/97).

**Comment by sbromberger** [comment] 2017-07-25 21:14
Sorry, @timholy - I'm using VS Code as my editor and testing in a REPL inside a terminal.

**Comment by timholy** [comment] 2017-07-25 21:18
OSX or something else? (OSX has exhibited particular challenges.)

**Comment by sbromberger** [comment] 2017-07-25 21:21
```
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

Also, the `@show` statement is really good, and I see when it fails the modified file doesn't get printed. It happened last when I comment out a println in the middle of a function's execution, and then save, but I can't seem to reproduce it at will.

**Comment by timholy** [comment] 2017-07-25 21:27
OK, drat. You can probably see this immediately from the source code, but just in case the logic is as follows:
- `@schedule` a task to `watch_file` the directory containing the source code
- when there's a change to the directory, check the modification time of every `watched_file` in the directory
- those that occurred within the last second or so, trigger a revision

So my hunch is that the error is in the "within the last second or so" part. (You can see more detail in https://github.com/timholy/Revise.jl/pull/22). Perhaps can you try increasing the tolerance to 2 secs, or other tweaks? It's difficult for me to try since I don't have access to OSX.

**Comment by sbromberger** [comment] 2017-07-25 22:16
I'm happy to give you a shell account on my OSX machine to test if you'd like....

**Comment by sbromberger** [comment] 2017-07-25 22:19
Also, not sure if this is relevant, but calling `revise()` manually doesn't actually cause the changes to be applied once things fail.

**Comment by timholy** [comment] 2017-07-25 22:34
> I'm happy to give you a shell account on my OSX machine to test if you'd like....

We might get to that, but this is probably a latency bug and I'm currently in Italy where the latency to the US is pretty high. Might be easier once I get back stateside.

> Also, not sure if this is relevant, but calling revise() manually doesn't actually cause the changes to be applied once things fail.

That's expected: `revise()` only parses files that have been added to `revision_queue`, and that only happens if the `mtime` criterion is satisfied at the time that the directory triggers the callback. Have you tried changing [this line](https://github.com/timholy/Revise.jl/blob/0ab150ed5320b01851b3962e4f4c3a61b2e0b233/src/Revise.jl#L431) to `mtime(path) + 2`? Or even `mtime(path) + 5`?

**Comment by sbromberger** [comment] 2017-07-25 22:56
Not yet. Give me a few minutes to debug the code I'm supposed to be working on right now and I'll test it later. Have fun in Italy!

**Comment by sbromberger** [comment] 2017-07-25 23:40
I think I can reproduce it. I have a `readline(STDIN)` at the bottom of a loop in my function. If I ^C out at that readline (incurring an `InterruptException`), then the next save I make isn't caught by revise.

**Comment by timholy** [comment] 2017-07-26 12:47
I tried to reproduce this with the following test script:
```julia
f(x) = 1
g(x) = 1

function getstuff()
    readline(STDIN)
end
```

And here's how I was testing it (you can probably guess the places where I went and saved an edit to the file):
```julia
julia> include("foo.jl")
getstuff (generic function with 1 method)

julia> Revise.track("foo.jl")

julia> g(1)
4

julia> g(1)
2

julia> getstuff()
hello
"hello"

julia> g(1)
3

julia> getstuff()
^CERROR: InterruptException:
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:216
 [3] wait(::Condition) at ./event.jl:27
 [4] wait_readbyte(::Base.TTY, ::UInt8) at ./stream.jl:273
 [5] readuntil(::Base.TTY, ::UInt8) at ./stream.jl:787
 [6] #readline#199(::Bool, ::Function, ::Base.TTY) at ./io.jl:190
 [7] readline(::Base.TTY) at ./io.jl:190
 [8] getstuff() at /tmp/foo.jl:5

julia> g(1)
3

julia> g(1)
5
```
So I can't reproduce the breakage, unfortunately. Any chance for an even more explicit demo?

(BTW, while debugging this I noticed an absolute-path problem, if you encounter it you can do a `Pkg.checkout("Revise", "teh/interrupts")` and it should fix the problem.)

**Comment by sbromberger** [comment] 2017-07-26 14:22
I'll be able to test more tonight, I think. Thanks for sticking with me. An idea: put variable assignments inside getstuff and make those the subject of your change. Interrupt at the readline. 

It's not 100% reproducible yet. I'm sorry for reporting a heisenbug.

**Comment by timholy** [comment] 2017-10-08 12:51
Might be fixed by #54?

**Comment by sbromberger** [comment] 2017-10-08 14:55
Happy to test. Will report back this week.

**Comment by shorty66** [comment] 2017-11-09 10:48
I have the same problem, but without the `readline()`. I am testing a while loop in VSCode using `@show` for debugging and if i ^C out of the running while loop, Revise stops working.

**Comment by timholy** [comment] 2017-11-09 11:40
A VS code specific workaround was just posted: https://github.com/JuliaEditorSupport/julia-vscode/wiki/Know-issues-and-workarounds

**Comment by YongHee-Kim** [comment] 2018-05-31 06:37
revise was working with VScode a month ago (I've been away from doing Julia for a while)
 
And It's not working on my machine now even with manual command.
![image](https://user-images.githubusercontent.com/7087745/40765765-7c63aa16-64e8-11e8-8077-012786187d51.png)


this is my versioninfo() 
```
Julia Version 0.6.3
Commit d55cadc350* (2018-05-28 20:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by timholy** [comment] 2018-12-29 15:14
Closing due to lack of recent reports or updates

**Closed by timholy** 2018-12-29 15:14 UTC
