### ISSUE TITLE
Revise on Core.Compiler not functional

### ISSUE THREAD

**Issue by vchuravy** [timholy/Revise.jl#270] opened 2019-04-03 14:51 UTC
I didn't see another issue for this yet, but with `Revise @ v2.0.5`

```
 Revise.track(Core.Compiler)
┌ Warning: Core.Compiler is disabled
└ @ Revise ~/.julia/packages/Revise/17Klc/src/recipes.jl:139
...
```

Downgrading to `Revise @ v1.1.0` allows the recipe to work.

**Comment by pfitzseb** [comment] 2019-04-03 14:57
This is basically a duplicate of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/242, I think.

**Comment by timholy** [comment] 2019-04-03 15:32
Yep. It already has a `@test_broken` for it.

**Comment by Keno** [comment] 2019-04-21 22:41
Since the linked issue is closed, does this work again :)?

**Comment by pfitzseb** [comment] 2019-04-22 08:17
Mostly: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/277

**Comment by timholy** [comment] 2019-04-22 08:50
See #289

**Closed** 2019-09-20 10:30 UTC
