### ISSUE TITLE
Revise doesn't work if I get a dependency warning

### ISSUE THREAD

**Issue by ExpandingMan** [timholy/Revise.jl#383] opened 2019-11-08 18:37 UTC
With Revise 2.2.0 and Julia 1.3-rc4, Revise seemed to not be working at all.  After some experimenting, I find that it only seems to not work if I get the following warning
```julia
┌ Warning: Package Arrow does not have Debugger in its dependencies:
│ - If you have Arrow checked out for development and have
│   added Debugger as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Arrow
└ Loading Debugger into Arrow from project dependency, future warnings for Arrow are suppressed.
```
This warning is of course generated because I have a package loading which calls `using Debugger` when `Debugger` is not listed in its dependencies in its `Manifest.toml`.  It's pretty inconvenient for Revise not to work when I get this warning, because of course I deliberately do not have Debugger in my dependencies because it's only for development.  Is it possible to get Revise to work even though this warning is thrown?

**Comment by ianshmean** [comment] 2019-11-08 23:15
Thanks for confirming this. I had a suspicion it was happening!

**Comment by timholy** [comment] 2019-11-09 06:41
Duplicate of #371.

**Closed by timholy** 2019-11-09 06:41 UTC
