### ISSUE TITLE
Could revise update docstrings as well?

### ISSUE THREAD

**Issue by juliohm** [timholy/Revise.jl#517] opened 2020-07-12 22:34 UTC
I often write docstrings incrementally and check the if they are properly highlighted on the REPL. Could Revise.jl notice changes in docstrings somehow?

**Comment by timholy** [comment] 2020-07-13 09:51
It should work find (see the `runtests.jl.` file and search for "doc"). The only known bug is #197. You'll have to provide a MWE so I can reproduce the problem you're seeing.

**Comment by timholy** [comment] 2020-09-09 13:12
Closing due to lack of reproducer.

**Closed by timholy** 2020-09-09 13:12 UTC
