### ISSUE TITLE
Julia 1.11: warning, precompile directives failed

### ISSUE THREAD

**Issue by mkitti** [timholy/Revise.jl#780] opened 2023-11-28 03:56 UTC
I have not investigated this thoroughly yet, but I've seen this a few times while using Julia 1.11.

```julia
julia> using SnoopCompile
Precompiling SnoopCompile
  30 dependencies successfully precompiled in 115 seconds. 32 already precompiled.
  1 dependency had output during precompilation:
┌ Revise
│  ┌ Warning: precompile directive
│  │     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, typeof(pairs(NamedTuple())), typeof(methods_by_execution!), Any, MI, DocExprs, Module, Expr})
│  │ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
│  └ @ Revise ~/.julia/packages/Revise/xRltd/src/precompile.jl:65
│  ┌ Warning: precompile directive
│  │     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:skip_include,), Tuple{Bool}}}, typeof(methods_by_execution!), Any, MI, DocExprs, Module, Expr})
│  │ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
│  └ @ Revise ~/.julia/packages/Revise/xRltd/src/precompile.jl:66
│  ┌ Warning: precompile directive
│  │     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, typeof(methods_by_execution!), Any, MI, DocExprs, Frame, Vector{Bool}})
│  │ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
│  └ @ Revise ~/.julia/packages/Revise/xRltd/src/precompile.jl:69
└  
[ Info: Precompiling SnoopCompile [aa65fe97-06da-5843-b5b1-d5d13cad87d2]

```

**Comment by IanButterworth** [comment] 2023-12-22 19:32
@timholy I spent some time trying to figure these out but couldn't. If you can give any guidance I can try again

**Comment by timholy** [comment] 2023-12-31 09:53
The issue is probably that `LoweredCodeUtils.bodymethod` fails on nightly. So presumably the first step is to get LoweredCodeUtils passing on nightly. Fair warning, fixing such issues can sometimes be a bit scary (e.g., https://github.com/JuliaDebug/LoweredCodeUtils.jl/issues/87). I may be able to take a look at it in the next few days.

**Comment by ctkelley** [comment] 2023-12-31 11:40
The good news is that revised still seems to work correctly.

**Comment by timholy** [comment] 2024-01-10 13:25
This will be fixed by https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/95. But I am a little reluctant to release it because I don't share @ctkelley's confidence; indeed, CI tells us that Revise is (partially) broken on nightly. The failures are reasonably isolated, so it may be OK in many situations, but this is still very much in a use-at-your-own-risk scenario.

**Comment by oscardssmith** [comment] 2024-02-07 19:24
should we merge that PR? Less broken seems like an improvement to me.

**Comment by timholy** [comment] 2024-07-20 09:16
Fixed by https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/108

**Closed by timholy** 2024-07-20 09:16 UTC
Labels: outside limit
