### ISSUE TITLE
Revise not tracking subdirectories inside WSL2 when updating LOAD_PATH variable

### ISSUE THREAD

**Issue by juandarias** [timholy/Revise.jl#615] opened 2021-03-24 14:51 UTC
- MWE

1) Create a subdirectory `src` or any other name in your working directory. The working directory has to be inside a mounted windows partition

2) Create a file `MyModule.jl` in subdirectory with content:

```
module MyModule

export anotherfunc

function anotherfunc(x)
    display(sin(x))
end

end
```

3) Run `julia` from working directory and execute following code:

```
push!(LOAD_PATH, pwd()*"/src")
using Revise
using MyModule
anotherfunc(0)
```

4) Edit `MyModule.jl` to `display(cos(x))`. Output of `anotherfunc(0)` in REPL doesn't change

- System

1. Julia 1.5.2
2. Revise 3.1.14
3. Ubuntu 18.04 in WSL2

**Comment by fredrikekre** [comment] 2021-03-24 14:56
Can't reproduce. Perhaps you were loading `MyModule` from an earlier entry in `LOAD_PATH`? What happens if you instead of `push!` use `pushfirst!`?

**Comment by juandarias** [comment] 2021-03-24 20:00
It seems to be because the folder and files were inside a mounted partition! 

So actually I am using WSL2 with Ubuntu 18.04, and the tests I performed were with files inside the mounted Windows partition. So any test with files inside "/mnt/c/" fails.

With files inside the Linux filesystem, the behavior of Revise is the correct.

Perhaps, this is not an issue of Revise at all.

**Comment by fredrikekre** [comment] 2021-03-24 23:10
Ok, probably #514 then?

**Comment by juandarias** [comment] 2021-03-25 06:24
Yes, that seems to be the problem. Only for the record, if the module is in the _working directory_ and not a _subdirectory_, the behaviour is the correct one.

**Comment by timholy** [comment] 2021-08-07 15:28
I'll close this as a near-duplicate of #514, but I linked back here for the info re subdirectories. Thanks to both!

**Closed by timholy** 2021-08-07 15:28 UTC
