### ISSUE TITLE
"Please report an issue in Revise"

### ISSUE THREAD

**Issue by Vilin97** [timholy/Revise.jl#819] opened 2024-05-31 03:59 UTC
Warning
```
vilin@doppio:~/GradientFlows.jl$ julia --threads=10
The latest version of Julia in the `beta` channel is 1.11.0-beta2+0.x64.linux.gnu. You currently have `1.11.0-beta1+0.x64.linux.gnu` installed. Run:

  juliaup update

in your terminal shell to install Julia 1.11.0-beta2+0.x64.linux.gnu and update the `beta` channel to that version.
Precompiling Revise...
Info Given Revise was explicitly requested, output will be shown live 
┌ Warning: precompile directive
│     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, typeof(pairs(NamedTuple())), typeof(methods_by_execution!), Any, MI, DocExprs, Module, Expr})
│ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
└ @ Revise ~/.julia/packages/Revise/bAgL0/src/precompile.jl:64
┌ Warning: precompile directive
│     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:skip_include,), Tuple{Bool}}}, typeof(methods_by_execution!), Any, MI, DocExprs, Module, Expr})
│ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
└ @ Revise ~/.julia/packages/Revise/bAgL0/src/precompile.jl:65
┌ Warning: precompile directive
│     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, typeof(methods_by_execution!), Any, MI, DocExprs, Frame, Vector{Bool}})
│ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
└ @ Revise ~/.julia/packages/Revise/bAgL0/src/precompile.jl:68
  1 dependency successfully precompiled in 10 seconds. 34 already precompiled.
  1 dependency had output during precompilation:
┌ Revise
│  [Output was shown above]
```
Version:
```
julia> versioninfo()
Julia Version 1.11.0-beta1
Commit 08e1fc0abb9 (2024-04-10 08:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 80 × Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, broadwell)
Threads: 10 default, 0 interactive, 5 GC (on 80 virtual cores)

(@v1.11) pkg> st Revise
Status `~/.julia/environments/v1.11/Project.toml`
  [295af30f] Revise v3.5.14
```

**Comment by longemen3000** [comment] 2024-06-27 23:59
same thing happens in 1.11 rc-1

**Comment by KronosTheLate** [comment] 2024-07-10 08:06
+1, same warnings on 1.11 rc1

**Comment by KronosTheLate** [comment] 2024-07-10 08:07
By the way, this is a duplicate of https://github.com/timholy/Revise.jl/issues/780

**Comment by timholy** [comment] 2024-07-20 09:16
Fixed by https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/108

**Closed by timholy** 2024-07-20 09:16 UTC
