### ISSUE TITLE
Whenever I edit a file Revise thinks I changed a struct definition

### ISSUE THREAD

**Issue by ejmeitz** [timholy/Revise.jl#772] opened 2023-11-07 01:42 UTC
I have the following class defined in a file:

```julia
struct ConstraintCluster{N}
    constraints::SVector{N,<:Constraint}
end
```

whenever I edit anything in this file Revise throws and error saying that I modified this struct and force me to restart the Julia instance. I have no idea why this is happening and its making development extremely painful. If anyone could help me diagnose the issue that would be great.

Error:

> ┌ Error: Failed to revise D:\Code\repos\Molly.jl\src\constraints\constraints.jl
> │   exception =
> │    invalid redefinition of type ConstraintCluster
> │    Stacktrace:
> │     [1] top-level scope
> │       @ none:0
> │    Revise evaluation error at D:\Code\repos\Molly.jl\none:0
> │ 
> └ @ Revise C:\Users\ejmei\.julia\packages\Revise\NiAIj\src\packagedef.jl:723   
>

**Comment by thofma** [comment] 2023-11-08 07:08
Dup of #734

**Comment by timholy** [comment] 2023-12-31 09:32
I can't test this explicit issue (what is `Constraint`?), but since it's a dup of #734 (which I cannot reproduce), I'll close this.

What I really, really need is a self-contained MWE that replicates the issue.

**Closed by timholy** 2023-12-31 09:32 UTC

**Comment by ejmeitz** [comment] 2024-01-11 01:17
I don't really have time to set-up a test package and verify that this is a MWE but here is the contents of the file up to the problematic class definition (`ConstraintCluster`). If I modify any of the code that exists below this struct definition Revise breaks. Sorry I don't have time to test but maybe there's something that jumps out to you from this.

```julia
export
    DistanceConstraint, 
    NoSystemConstraints,
    n_dof


"""
Supertype for all constraint algorithms.
"""
abstract type ConstraintAlgorithm end
abstract type PositionConstraintAlgorithm <: ConstraintAlgorithm end
abstract type PositionAndVelocityConstraintAlgorithm <: ConstraintAlgorithm end

ConstrainsPositions = Union{PositionConstraintAlgorithm, PositionAndVelocityConstraintAlgorithm}

"""
Placeholder struct for [`System`](@ref) constructor when the system does not require constraints.
An example of a constraint algorithm is [`SHAKE`](@ref).
"""
struct NoSystemConstraints <: ConstraintAlgorithm end


"""
Supertype for all types of constraint.
"""
abstract type Constraint end

"""
Constraint between two atoms that maintains the distance between the two atoms.
# Arguments
- `atom_idxs::SVector{Int}` : The indices of atoms in the system participating in this constraint
- `dist::D` : Euclidean distance between the two atoms.
"""
struct DistanceConstraint{D} <: Constraint
    atom_idxs::SVector{2,<:Integer}
    dist::D
end

"""
Atoms in a cluster do not participate in any other constraints outside of that cluster.
"Small" clusters contain at most 4 bonds between 2,3,4 or 5 atoms around one central atom.
Small clusters include: 1 bond, 2 bonds, 1 angle, 3 bonds, 1 bond 1 angle, 4 bonds
Note that an angle constraints will be implemented as 3 distance constraints. These constraints
use special methods that improve computational performance. Any constraint not listed above
will come at a performance penatly.
"""
struct ConstraintCluster{N}
    constraints::SVector{N,<:Constraint}
end
```
