### ISSUE TITLE
Revise not working anymore for files that contain type definition (but the type is not changed)

### ISSUE THREAD

**Issue by thofma** [timholy/Revise.jl#734] opened 2023-02-21 10:40 UTC
I noticed a regression with files that contain type definitions.

I have a file, which contains a type definition
```
mutable struct A
  x
end
```
and some method definitions
```
function g()
end
```
If the file is tracked with Revise and I change `g`, I get:
```
┌ Error: Failed to revise ...
│   exception =
│    invalid redefinition of constant A
```
which I did not expect, since I did *not* change the type definition. This is with Revise version 3.5.1.

I quickly tried with Revise version 3.4.0 and it is working as expected. This means, that when only `g` is changed but not `A`, then the file is revised properly.

**Comment by lgoettgens** [comment] 2023-03-06 16:34
The same thing happened to me. However, it only occurs in a subset of the files of the given structure, and I cannot find any way to distinguish them.
Pinning the version to 3.4.0 seems to be a workaround for now, thanks for the tip @thofma .

**Comment by fingolfin** [comment] 2023-03-22 13:45
@timholy any idea what might be causing this?

**Comment by timholy** [comment] 2023-03-22 14:54
I need to spend a week or so on Revise. No time right now though.

**Comment by kahaaga** [comment] 2023-12-13 11:29
Same issue here with Revise v3.5.10. 

I'm tracking changes in a package I'm developing. Any change to any file that contains a type definition triggers the same error as above. 

The following workaround solves it for me (thanks, @fingolfin):

```julia
(@v1.9) pkg> activate . # in whatever project folder you're working
(MyProject) pkg> add JuliaInterpreter@0.9.26
(MyProject) pkg> add Revise@3.4.0
julia> using Revise, MyProject
```

**Comment by timholy** [comment] 2023-12-30 23:20
At least with Julia 1.10 and LoweredCodeUtils 2.4.0, I cannot replicate this. Here's my setup:
```julia
tim@diva:/tmp/TestRevise$ ls -l
total 12
-rw-r--r-- 1 tim tim  186 Dec 30 10:36 Manifest.toml
-rw-r--r-- 1 tim tim  128 Dec 30 10:35 Project.toml
drwxr-xr-x 2 tim tim 4096 Dec 30 10:35 src
tim@diva:/tmp/TestRevise$ cat src/TestRevise.jl
module TestRevise

export g

mutable struct A
    x
end

function g()
end

end # module TestRevise
```
And then
```julia
julia> using TestRevise
Precompiling TestRevise
  1 dependency successfully precompiled in 1 seconds

julia> g()

# Now edit `g` to return 1
julia> 1+1
2

julia> g()
1
```

All seems working as expected.

**Comment by aviatesk** [comment] 2023-12-31 00:35
I haven't been able to replicate this issue with Julia 1.10 and the latest versions of Revise and its dependencies. So it seems reasonable to close the issue at this point.

**Closed** 2023-12-31 02:05 UTC

**Comment by thofma** [comment] 2023-12-31 10:02
I can still reproduce this, although with a slightly more complicated file. I will try to find a small example.

**Comment by thofma** [comment] 2023-12-31 12:19
With the following, it still fails for me:
```
 /tmp/TestRevise  cat src/TestRevise.jl
module TestRevise

abstract type A{S, T} end

mutable struct B{S} <: A{S, B}
end

g() = 2

end # module TestRevise
```

```
julia> TestRevise.g()
1

# Now edit g
julia> 1 + 1
 Error: Failed to revise /tmp/TestRevise/src/TestRevise.jl
│   exception =
│    invalid redefinition of constant TestRevise.B
│    Stacktrace:
│     [1] top-level scope
│       @ /tmp/TestRevise/src/TestRevise.jl:5
│    Revise evaluation error at /tmp/TestRevise/src/TestRevise.jl:5
```
Can you reproduce @aviatesk?

**Comment by lgoettgens** [comment] 2024-01-05 11:51
I can reproduce it with the mwe from https://github.com/timholy/Revise.jl/issues/734#issuecomment-1872935042. with Revise v3.5.12 and JuliaInterpreter v0.9.27.

The workaround from https://github.com/timholy/Revise.jl/issues/734#issuecomment-1836244110 unfortunately no longer works for me.

**Comment by thofma** [comment] 2024-01-05 11:54
It is a dup of https://github.com/timholy/Revise.jl/issues/770

**Comment by lgoettgens** [comment] 2024-01-05 12:26
I don't think so. I compiled julia with https://github.com/JuliaLang/julia/pull/52748 and the example from https://github.com/timholy/Revise.jl/issues/770#issue-1962977993 is fixed, but the one from https://github.com/timholy/Revise.jl/issues/734#issuecomment-1872935042 still fails
