### ISSUE TITLE
Revise.jl with Parameters.jl erroneous “invalid redefinition of constant” in 1.3.1

### ISSUE THREAD

**Issue by a-torgovitsky** [timholy/Revise.jl#420] opened 2020-02-11 18:13 UTC
This was originally posted on Discourse:
https://discourse.julialang.org/t/revise-jl-with-parameters-jl-erroneous-invalid-redefinition-of-constant-in-1-3-1/34475

-----------------

Code sample
```julia
module ReviseBehavior

using Parameters

@with_kw struct MyStruct
    x::Array{<:Real, 1} = [.05]
end
export MyStruct

function foo()
    print("hello")
end
export foo

end
```

My action in the REPL:
```julia
julia> using ReviseBehavior
[ Info: Precompiling ReviseBehavior [top-level]

# here I go and change "hello" to "hello world" in ReviseBehavior.jl
julia> foo()
```

Expected outcome:
```julia
hello world
```

I do get this outcome on Julia 1.1 with Revise 2.4
```
(v1.1) pkg> status Revise Parameters
    Status `~/.julia/environments/v1.1/Project.toml`
  [d96e819e] Parameters v0.12.0
  [295af30f] Revise v2.4.0
```

However, with Julia 1.3.1 and Revise 2.5 
```
(v1.3) pkg> status Revise Parameters
    Status `~/.julia/environments/v1.3/Project.toml`
  [d96e819e] Parameters v0.12.0
  [295af30f] Revise v2.5.0
```

I get this outcome
```julia
┌ Error: Failed to revise /home/at/Desktop/revise-behavior/ReviseBehavior.jl
│   exception =
│    invalid redefinition of constant MyStruct
│    Stacktrace:
│     [1] top-level scope at REPL[1]:0
└ @ Revise ~/.julia/packages/Revise/S7mrl/src/Revise.jl:590
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│
│   /home/at/Desktop/revise-behavior/ReviseBehavior.jl
│
│ Use Revise.errors() to report errors again.
└ @ Revise ~/.julia/packages/Revise/S7mrl/src/Revise.jl:639
hello
```

**Comment by a-torgovitsky** [comment] 2020-02-11 18:18
I tried downgrading Revise to 2.4 on Julia 1.3 and I get the same issue.

**Comment by timholy** [comment] 2020-02-15 14:47
Thanks for the bug report. It looks like I broke this with JuliaInterpreter 0.7.10; should be fixed in https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/379, which should be released in JuliaInterpreter 0.7.12.

**Comment by sshin23** [comment] 2020-09-25 15:26
This issue seems to be appearing again with Revise.jl `>= v3.0.0` (the same example above can be used to reproduce the issue). Revise works fine with Parameters.jl until `<= v2.7.6`.

**Closed** 2020-10-04 13:06 UTC

**Comment by timholy** [comment] 2020-10-04 13:07
Sorry this took so long, it was a pretty brutal bug to track down. It turns out LoweredCodeUtils was doing some pretty insane stuff, so definitely good riddance. Thanks for reporting it!

**Comment by oschulz** [comment] 2020-10-07 03:33
Ran into the same thing, today - updated to LoweredCodeUtils.jl v1.2.3, problem gone. Thanks so much, @timholy, Revise is awesome!
