### ISSUE TITLE
Error in multiple environments

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#205] opened 2018-10-26 14:56 UTC
When I have multiple terminals open in different environments, I frequently get errors of the form

```julia
ERROR: /home/cst-jean/.julia/dev/Foo/src/foo.jl is not stored in the source-text cache
Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] _read_dependency_src(::IOStream, ::String) at ./loading.jl:1308
 [3] read_dependency_src(::IOStream, ::String) at ./loading.jl:1294
 [4] read_dependency_src(::String, ::String) at ./loading.jl:1315
 [5] read_from_cache(::Revise.FileInfo, ::String) at /home/cst-jean/.julia/packages/Revise/TmjcT/src/pkgs.jl:156
 [6] maybe_parse_from_cache!(::Revise.FileInfo, ::String) at /home/cst-jean/.julia/packages/Revise/TmjcT/src/pkgs.jl:162
 [7] revise_file_now(::String) at /home/cst-jean/.julia/packages/Revise/TmjcT/src/Revise.jl:413
 [8] revise(::REPL.REPLBackend) at /home/cst-jean/.julia/packages/Revise/TmjcT/src/Revise.jl:470
 [9] run_backend(::REPL.REPLBackend) at /home/cst-jean/.julia/packages/Revise/TmjcT/src/Revise.jl:764
 [10] (::getfield(Revise, Symbol("##58#60")){REPL.REPLBackend})() at ./task.jl:259
```

I can reproduce this consistently, by doing:

1. Open julia window #1. `using Revise, Foo` in the default environment, where Foo is `dev`ed
2. Open julia window #2. `activate OtherEnv; using Foo`.  Foo is not `dev`ed in this environment (eg. on `Foo#master`)
3. Modify `Foo`'s source code
4. Type anything in window #1 to trigger Revise

**Comment by timholy** [comment] 2018-10-31 13:56
Thanks for a great bug report. I'll look into it while also working on #146.

**Comment by timholy** [comment] 2018-12-30 11:04
So, it turns out this is the same as https://github.com/JuliaLang/julia/issues/27418.

Until that's fixed, the perfect fix here doesn't exist. The only one that would be robust would be to run Revise in "eager-parsing" mode, meaning that for every package you use, it parses the entire cache file immediately rather than waiting until something changes. Except for race conditions between two Julia sessions, that would "free" Revise from depending on the source-text cache.

The downside of such a workaround is that Revise will be a heavier dependency, because it will do a lot more parsing. To prevent the cost from affecting everyone, I can make a switch that you can set in your `startup.jl`. If you want to experiment with this, try this diff:

```diff
diff --git a/src/pkgs.jl b/src/pkgs.jl
index 60c2c16..a51226b 100644
--- a/src/pkgs.jl
+++ b/src/pkgs.jl
@@ -83,6 +83,7 @@ function parse_pkg_files(id::PkgId)
                         # For precompiled packages, we can read the source later (whenever we need it)
                         # from the *.ji cachefile.
                         pkgdata.fileinfos[fname] = FileInfo(mod, path)
+                        maybe_parse_from_cache!(pkgdata, fname)
                         push!(files, fname)
                     end
                     return files
```

If you like it, a PR to enable it via a switch would be welcome (or I will do it if you ask), e.g., like those  [here](https://github.com/timholy/Revise.jl/blob/09a3d35739e8e7d75e3dc021da1be7b6c361ee7c/src/Revise.jl#L11-L55).

**Comment by cstjean** [comment] 2018-12-30 19:03
Thank you. I've changed my workflow to deal with the issue otherwise, so I don't need it at the moment.

**Comment by timholy** [comment] 2019-04-08 09:41
I'll close this since the best fix is just to fix JuliaLang/julia#27418.

**Closed by timholy** 2019-04-08 09:41 UTC

**Comment by yha** [comment] 2019-12-19 12:30
I'm experiencing a similar issue, though under different circumstances (I haven't looked into consistently reproducing it yet, but my setup is not consistent with that described above).
I am using Julia 1.1.1. Am I correct in understanding that fixing this requires either moving to Julia 1.3 (where JuliaLang/julia#27418 is fixed) or the workaround described here? Or should I file a new issue?

**Comment by timholy** [comment] 2019-12-20 11:37
This is a won't-fix in Revise (the fix would absolutely cripple Revise for the majority of users), so you'll need to find another workaround.
